# Homework #3: Поиск максимального собственного числа

Python 3.6 17.10.2017 Bykov Kirill

## 1. Степенной метод

In [1]:
#imports
import numpy as np
from numpy import linalg as LA
import time

In [2]:
A = np.matrix([[0.72, 0.45 , 0.38], [0.45, 0.91, .56], [0.38, 0.56, 0.12]])
eps = 0.00000000000001

print(A)

[[ 0.72  0.45  0.38]
 [ 0.45  0.91  0.56]
 [ 0.38  0.56  0.12]]


In [3]:
y_curr = np.matrix([1.,1.,1.]).T

In [4]:
lambda_curr = 0
lambda_prev = 2*eps
start_time = time.time()
while (abs(lambda_curr - lambda_prev)>eps):
    y_prev = np.copy(y_curr)
    lambda_prev = lambda_curr
    y_curr = np.dot(A,y_prev)
    lambda_curr = y_curr[1,0]/y_prev[1,0]
print(lambda_curr)
print("--- %s seconds ---" % (time.time() - start_time))

1.58570573325
--- 0.003002643585205078 seconds ---


#### Проверка

In [5]:
w, v = LA.eig(A)
print(w)

[ 1.58570573  0.35958273 -0.19528847]


## 2. Метод скалярных произведений

In [6]:
A = np.matrix([[0.72, 0.45 , 0.38], [0.45, 0.91, .56], [0.38, 0.56, 0.12]])
A_1 = np.matrix([[0.72, 0.45 , 0.38], [0.45, 0.91, .56], [0.38, 0.56, 0.12]])
eps = 0.000000000001

In [7]:
Y_curr = np.matrix([1.,1.,1.]).T
Z_curr = np.matrix([1.,1.,1.]).T
Y_curr.shape

(3, 1)

In [8]:
lambda_curr = 0
lambda_prev = 2*eps
start_time = time.time()
while (abs(lambda_curr - lambda_prev)>eps):
    lambda_prev = lambda_curr
    Y_prev = np.copy(Y_curr)
    Z_prev = np.copy(Z_curr)
    
    Y_curr = np.dot(A,Y_curr)
    Z_curr = np.dot(A_1,Z_curr)
    
    lambda_curr = sum(Y_curr[i,0]*Z_curr[i,0] for i in range(Y_curr.shape[0])) / sum(Y_prev[i,0]*Z_curr[i,0] for i in range(Y_prev.shape[0]))
    
print(lambda_curr)
print("--- %s seconds ---" % (time.time() - start_time))

1.58570573325
--- 0.0015010833740234375 seconds ---
