# Homework #4

30.10.2017
Python 3.6

## Jacobi method
### Через перемножение матриц

In [1]:
#imports
import numpy as np
from numpy import linalg as LA
import time
import math

In [2]:
A = np.matrix([[0.72, 0.45 , 0.38], [0.45, 0.91, .56], [0.38, 0.56, 0.12]])

A

matrix([[ 0.72,  0.45,  0.38],
        [ 0.45,  0.91,  0.56],
        [ 0.38,  0.56,  0.12]])

In [3]:
def max_nondiogonal_element(matrix):
    n = matrix.shape[0]
    max = [matrix[0,1], 0, 1]
    for i in range(0,n):
        for c in range(i+1,n):
            if abs(matrix[i,c])>abs(max[0]):
                max = [matrix[i,c], i, c]
    return [max[1],  max[2]]

def nondiogonal_square_sum(matrix):
    n = matrix.shape[0]
    return 2 * sum(matrix[i,j]*matrix[i,j] for i in range(0,n) for j in range(i+1,n))

In [4]:
print(max_nondiogonal_element(A))
print(nondiogonal_square_sum(A))
print(A.shape)

[1, 2]
1.321
(3, 3)


In [10]:
eps = 0.00000001

n = A.shape[0]
C = np.copy(A)
C_prev = np.zeros(C.shape)
counter = 0
print(A)
while (nondiogonal_square_sum(C) > eps):
    C_prev = np.copy(C)
    a = max_nondiogonal_element(C)
    i = a[0]
    j = a[1]
    T = np.identity(n)
    d = math.sqrt((C[i, i] - C[j, j]) * (C[i, i] - C[j, j]) + 4. * C[i,j] * C[i,j])
    cos_phi = math.sqrt((1. + abs(C[i, i] - C[j, j]) / d) /2.)
    sin_phi = np.sign(C[i,j] * (C[i, i] - C[j, j])) * math.sqrt((1 - np.abs(C[i, i] - C[j, j]) / d) /2.)
    T[i, i] = cos_phi
    T[j, j] = cos_phi
    T[j, i] = sin_phi
    T[i, j] = -sin_phi
    C = T.transpose() @ C @ T
    counter += 1
    print("---")
    print(C)

print(counter)
result_m = [C[i,i] for i in range(n)]
print(result_m)

[[ 0.72  0.45  0.38]
 [ 0.45  0.91  0.56]
 [ 0.38  0.56  0.12]]
---
[[  7.20000000e-01   5.74395680e-01   1.30267428e-01]
 [  5.74395680e-01   1.20029191e+00   1.11022302e-16]
 [  1.30267428e-01   4.16333634e-17  -1.70291909e-01]]
---
[[ 0.33757027  0.          0.10843266]
 [ 0.          1.58272163  0.07219391]
 [ 0.10843266  0.07219391 -0.17029191]]
---
[[  3.59752640e-01   1.44692402e-02   0.00000000e+00]
 [  1.44692402e-02   1.58272163e+00   7.07290766e-02]
 [  3.46944695e-17   7.07290766e-02  -1.92474274e-01]]
---
[[  3.59752640e-01   1.44578054e-02  -5.75130349e-04]
 [  1.44578054e-02   1.58553523e+00   8.04911693e-16]
 [ -5.75130349e-04   7.44196371e-16  -1.95287871e-01]]
---
[[  3.59582138e-01  -1.69916164e-15  -5.75090360e-04]
 [ -1.67921232e-15   1.58570573e+00  -6.78210656e-06]
 [ -5.75090360e-04  -6.78210656e-06  -1.95287871e-01]]
---
[[  3.59582734e-01   7.02924435e-09   5.99786063e-15]
 [  7.02924437e-09   1.58570573e+00  -6.78210292e-06]
 [  6.03263641e-15  -6.78210292e-0

### В явном виде

#### n = A.shape[0]
C = np.copy(A)
counter = 0
while (nondiogonal_square_sum(C) > eps):
    C_prev = np.copy(C)
    a = max_nondiogonal_element(C_prev)
    i = a[0]
    j = a[1]
    d = math.sqrt((C_prev[i, i] - C_prev[j, j]) * (C_prev[i, i] - C_prev[j, j]) + 4. * C_prev[i,j] * C_prev[i,j])
    cos_phi = math.sqrt((1. + abs(C_prev[i, i] - C_prev[j, j]) / d) /2.)
    sin_phi = np.sign(C_prev[i,j] * (C_prev[i, i] - C_prev[j, j])) * math.sqrt((1 - np.abs(C_prev[i, i] - C_prev[j, j]) / d) /2.)
    for k in range(0,n):
        if (k!=i):
            C[k, i] = C_prev[k, i] * cos_phi + C_prev[k, j] * sin_phi
            C[i, k] = C[k,i]
    for k in range(0,n):
        if (k!=j) and (k!=i):
            C[k, j] = -C_prev[k, i] * sin_phi + C_prev[k, j] * cos_phi
            C[j, k] = C[k,j]
    C[i, i] = ((C_prev[i, i] + C_prev[j, j]) + np.sign(C_prev[i, i] - C_prev[j, j]) * d) / 2.
    C[j, j] = ((C_prev[i, i] + C_prev[j, j]) - np.sign(C_prev[i, i] - C_prev[j, j]) * d) / 2.
    C[i, j] = 0.
    C[j, i] = 0.
    counter += 1
    print(C)

print(counter)
result_f = [C[i,i] for i in range(n)]
print(result_f)

#### Проверка

In [8]:
w, v = LA.eig(A)
print(w)

[ 1.58570573  0.35958273 -0.19528847]
