# Homework #4

30.10.2017
Python 3.6

## Jacobi method
### Через перемножение матриц

In [95]:
#imports
import numpy as np
from numpy import linalg as LA
import time

In [96]:
A = np.matrix([[0.72, 0.45 , 0.38], [0.45, 0.91, .56], [0.38, 0.56, 0.12]])
eps = 0.00001

A

matrix([[ 0.72,  0.45,  0.38],
        [ 0.45,  0.91,  0.56],
        [ 0.38,  0.56,  0.12]])

In [97]:
def max_nondiogonal_element(matrix):
    n = matrix.shape[0]
    max = [matrix[0,1], 0, 1]
    for i in range(0,n):
        for c in range(i+1,n):
            if matrix[i,c]>max[0]:
                max = [matrix[i,c], i, c]
    return [max[1],  max[2]]

In [98]:
print(max_nondiogonal_element(A))
print(A.shape)

[1, 2]
(3, 3)


In [99]:
n = A.shape[0]
C = np.copy(A)
C_prev = np.zeros(C.shape)
counter = 0
while (abs(C[0,0] - C_prev[0,0]) > eps):
    C_prev = np.copy(C)
    a = max_nondiogonal_element(C)
    i = a[0]
    j = a[1]
    T = np.identity(n)
    d = np.sqrt((C[i, i] - C[j, j]) * (C[i, i] - C[j, j]) + 4 * C[i,j] * C[i,j])
    cos_phi = np.sqrt((1 + np.abs(C[i, i] - C[j, j]) / d) /2.)
    sin_phi = np.sign(C[i,j] * (C[i, i] - C[j, j])) * np.sqrt((1 - np.abs(C[i, i] - C[j, j]) / d) /2.)
    T[i, i] = cos_phi
    T[j, j] = cos_phi
    T[j, i] = sin_phi
    T[i, j] = -sin_phi
    C = T.transpose() @ C @ T
    counter += 1

print(counter)
result_m = [C[i,i] for i in range(n)]
print(result_m)

1
[0.71999999999999997, 1.2002919086053767, -0.17029190860537674]


### В явном виде

In [100]:
n = A.shape[0]
C = np.copy(A)
C_prev = np.zeros(C.shape)
counter = 0
while (abs(C[0,0] - C_prev[0,0]) > eps):
    C_prev = np.copy(C)
    a = max_nondiogonal_element(C_prev)
    i = a[0]
    j = a[1]
    d = np.sqrt((C_prev[i, i] - C_prev[j, j]) * (C_prev[i, i] - C_prev[j, j]) + 4 * C_prev[i,j] * C_prev[i,j])
    cos_phi = np.sqrt((1 + np.abs(C[i, i] - C[j, j]) / d) /2.)
    sin_phi = np.sign(C[i,j] * (C[i, i] - C[j, j])) * np.sqrt((1 - np.abs(C[i, i] - C[j, j]) / d) /2.)
    for k in range(0,n):
        if k!=i:
            C[k, i] = C_prev[k, i] * cos_phi +C[k, j] * sin_phi
            C[i, k] = C[k,i]
            if k!=j:
                C[k, j] = -C_prev[k, j] * sin_phi +C[k, j] * cos_phi
                C[j, k] = C[k,j]
    C[i, i] = ((C_prev[i, i] + C_prev[j, j]) + np.sign(C_prev[i, i] - C_prev[j, j]) * d) / 2.
    C[j, j] = ((C_prev[i, i] + C_prev[j, j]) - np.sign(C_prev[i, i] - C_prev[j, j]) * d) / 2.
    C[i, j] = 0
    C[j, i] = 0
    counter += 1
    print(C)

print(counter)
result_f = [C[i,i] for i in range(n)]
print(result_f)

[[ 0.72        0.57439568  0.16248277]
 [ 0.57439568  1.20029191  0.        ]
 [ 0.16248277  0.         -0.17029191]]
1
[0.71999999999999997, 1.2002919086053767, -0.1702919086053768]


#### Проверка

In [101]:
w, v = LA.eig(A)
print(w)

[ 1.58570573  0.35958273 -0.19528847]
